[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist" # Change this based on your build output directory (e.g., "build" or "out")

[functions]
  external_node_modules = ["nodemailer"]
  directory = "netlify/functions"
  node_bundler = "esbuild"